name: Build and Publish Docker Image

on: push

jobs:
  build:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Build and publish Docker Image to new GitHub Packages Registry
        uses: DrSkunk/gp-docker-action@1.1.9
        with:
          github-token: ${{ github.token }}
          image-name: exercise
          build-context: ../../sample-packages/docker/Dockerfile
