name: Build and Publish Docker Image

on: push

jobs:
  build:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build Tag Publish
        uses: bitovi/github-actions-docker-publish@v1.0.2
        with:
          checkout: true
          registry: ghcr.io
          docker_username: lbourgogn
          docker_password: ${{ github.token }}
