name: Build and Publish Docker Image

on: push

jobs:
  build:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: push-to-ghcr
        uses: macbre/push-to-ghcr@v8
        with:
          github_token: ${{ github.token }}
          image_name: lbourgogne/publlish-packages-exercise
          dockerfile: ../../sample-packages/docker/Dockerfile
          # optional, default is ./Dockerfile
